####
GET http://127.0.0.1:8000/form_memo?id=5
Accept: application/application/json

####
POST http://127.0.0.1:8000/form_memo
Accept: application/json
Content-Type: application/json

{
  "CREATOR": {
    "DEPARTMENT": "",
    "ID": 2,
    "NAME": "",
    "PATRONYMIC": "",
    "SURNAME": ""
  },
  "DATE_OF_APPOINTMENT": "2025-01-01",
  "DATE_OF_CREATION": "",
  "DESCRIPTION": [
    {
      "COEF": 0.0,
      "CONTRACT": 0,
      "COUNT": 5,
      "DATE_OF_DELIVERY": "2024-12-31",
      "ID": 0,
      "NAME": "Картошка",
      "POSITION": 1,
      "STATUS_CODE": 1,
      "STATUS_TEXT": "",
      "UNIT_CODE": 3,
      "UNIT_TEXT": ""
    },
    {
      "COEF": 0.0,
      "CONTRACT": 0,
      "COUNT": 5,
      "DATE_OF_DELIVERY": "2024-12-31",
      "ID": 0,
      "NAME": "Свёкла",
      "POSITION": 1,
      "STATUS_CODE": 1,
      "STATUS_TEXT": "",
      "UNIT_CODE": 3,
      "UNIT_TEXT": ""
    }
  ],
  "EXECUTOR": {
    "DEPARTMENT": "",
    "ID": 1,
    "NAME": "",
    "PATRONYMIC": "",
    "SURNAME": ""
  },
  "ID_MEMO": 0,
  "INFO": "Тестовая заявка",
  "STATUS_CODE": 1,
  "STATUS_TEXT": ""
}


####
GET http://127.0.0.1:8000/get_selectors
Accept: application/application/json

####
GET http://127.0.0.1:8000/form_memo?id=12
Accept: application/application/json

###
POST http://127.0.0.1:8000/register
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test52",
  "PASSWORD": "abcd1234",
  "EMAIL": "test52@mail.ru",
  "ROLE_ID": 5,
  "PHONE": "+7987-564-32-17"
}

###
POST http://127.0.0.1:8000/login
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test51",
  "PASSWORD": "abcd1234"
}

###e
GET http://127.0.0.1:8000/get_user_info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzA2NTQwOSwianRpIjoiMTY3ZDE4NjYtMTVkMS00YWI3LTk0Y2QtMjZmMTRkMzI5YWE4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QxIiwibmJmIjoxNzMzMDY1NDA5LCJjc3JmIjoiMzAyMzBjNGQtZWViOS00Mjk2LWFjNDgtNTBlYWIxOWJmYmRlIiwiZXhwIjoxNzMzMDcyNjA5LCJyb2xlX2lkIjoxLCJpZCI6MX0.iWcxQv8BUf2CHd1a7uo622n6KTzidBexBJAGlpOW7mo


###
GET http://127.0.0.1:8000/get_reestr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzY5MTU4MCwianRpIjoiNTFmZDM5ODUtYWEzNS00NmY3LWJkMGYtZmM2Yzg5YTRmMTQ4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MSIsIm5iZiI6MTczMzY5MTU4MCwiY3NyZiI6IjIyNjY5ZDc2LTgwM2YtNGNlNS1hOTAwLTA4MTMwYWFlNDU0YyIsImV4cCI6MTczMzY5ODc4MCwicm9sZV9pZCI6NSwiaWQiOjExfQ.gDgfKKMWHQQHh9AJIL8fP4PlyK0Cj2ta_i4jm-glsyw

###
GET http://127.0.0.1:8000/accept_memo?id=1&accept=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzU3Mjk2MywianRpIjoiZjVhZWVjMjMtY2Q0NS00YWRiLWI0NmEtYTkxNjI0ZGY3YzczIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzMzNTcyOTYzLCJjc3JmIjoiMTgyNGU4ZWItZDgxYi00ODg5LWJiNzctYzFhNDY0M2U0N2VlIiwiZXhwIjoxNzMzNTgwMTYzLCJyb2xlX2lkIjoyLCJpZCI6N30.rNfZkiJtim6LZTZgq9W5BE0ImjsFufMEhiIvO11Ggrc


###
GET http://127.0.0.1:8000/search_memo?filters={"ITEM_NAME": "Ка"}
Accept: application/application/json


###
POST http://127.0.0.1:8000/set_sop?id=46
Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8000/get_aggregate
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzY3NTU1OCwianRpIjoiYjdlYmM0OTQtODc2Yi00NThiLTlkOGUtZjI2MTc4MjI5M2I3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MSIsIm5iZiI6MTczMzY3NTU1OCwiY3NyZiI6IjAyNTYyN2VkLTA5M2UtNDMyMC1hNTMwLWFmYzAwOTMyMmJhNCIsImV4cCI6MTczMzY4Mjc1OCwicm9sZV9pZCI6NSwiaWQiOjExfQ.4WuOxTm1GpDYnKPVTne_OGU7G5ijIpJzmJZOVfyFwFM