####
GET http://127.0.0.1:8000/memo/form?id=0043
Accept: application/application/json

####
POST http://127.0.0.1:8000/memo/form
Accept: application/json
Content-Type: application/json

{
  "ID_MEMO": 0,
  "DATE_OF_CREATION": "2024-10-27",
  "DATE_OF_APPOINTMENT": "2025-01-15",
  "STATUS_CODE": 1,
  "STATUS_TEXT": "Исполнение",
  "INFO": "ААААА",
  "JUSTIFICATION": "Описание для описаний",
  "HEAD_COMMENT": "",
  "EXECUTOR_COMMENT": "",
  "CREATOR": {
    "ID": 4,
    "SURNAME": "Петрова",
    "NAME": "Мария",
    "PATRONYMIC": "Александровна",
    "DEPARTMENT": "Отдел разработки IT-продуктов",
    "PHONE": "+7987-564-32-14",
    "EMAIL": "test4@mail.ru"
  },
  "EXECUTOR": {
    "ID": 7,
    "SURNAME": "Федорова",
    "NAME": "Анна",
    "PATRONYMIC": "Сергеевна",
    "DEPARTMENT": "Отдел 13"
  },
  "DESCRIPTION": [
    {
      "ID": 0,
      "POSITION": 1,
      "NAME": "Унитаз",
      "COUNT": 1,
      "UNIT_CODE": 6,
      "UNIT_TEXT": "ШТ",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "",
      "COEF": null,
      "CONTRACT_INFO": "",
      "DATE_OF_DELIVERY": "2025-12-12",
      "CONTRACT_TYPE": "",
      "EXECUTOR": {
        "ID": 11,
        "SURNAME": "Новиков",
        "NAME": "Олег",
        "PATRONYMIC": "Геннадьевич",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-15",
        "EMAIL": "test51@mail.ru"
      },
      "HISTORY": []
    }
  ],
  "JUSTIFICATION_FILE": {
    "EXT": null,
    "NAME": null,
    "DATA": null
  }
}

####
POST http://127.0.0.1:8000/memo/form
Accept: application/json
Content-Type: application/json

{
  "ID_MEMO": 0,
  "DATE_OF_CREATION": "2025-01-20",
  "DATE_OF_APPOINTMENT": "2025-01-10",
  "STATUS_CODE": 1,
  "STATUS_TEXT": "Ожидание согласования",
  "INFO": "Новая на проверк",
  "JUSTIFICATION": "Проверка фильтра",
  "HEAD_COMMENT": "",
  "EXECUTOR_COMMENT": "",
  "CREATOR": {
    "ID": 3,
    "SURNAME": "Сидоров",
    "NAME": "Петр",
    "PATRONYMIC": "Алексеевич",
    "DEPARTMENT": "Цех 1",
    "PHONE": "",
    "EMAIL": ""
  },
  "EXECUTOR": {
    "ID": 7,
    "SURNAME": "Федорова",
    "NAME": "Анна",
    "PATRONYMIC": "Сергеевна",
    "DEPARTMENT": "Отдел 13"
  },
  "DESCRIPTION": [
    {
      "ID": 0,
      "POSITION": 2,
      "NAME": "Соль",
      "COUNT": 15,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "DATE_OF_DELIVERY": "2025-01-17",
      "CONTRACT_TYPE": "",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    },
    {
      "ID": 0,
      "POSITION": 3,
      "NAME": "Мука",
      "COUNT": 25,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "CONTRACT_TYPE": "",
      "DATE_OF_DELIVERY": "2025-01-22",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    },
    {
      "ID": 100,
      "POSITION": 1,
      "NAME": "Соль",
      "COUNT": 20,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "CONTRACT_TYPE": "",
      "DATE_OF_DELIVERY": "2025-01-12",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    }
  ],
  "JUSTIFICATION_FILE": {
    "EXT": null,
    "NAME": null,
    "DATA": null
  }
}


####
GET http://127.0.0.1:8000/selector/get_all
Accept: application/application/json

####
GET http://127.0.0.1:8000/memo/form?id=19
Accept: application/application/json

###
POST http://127.0.0.1:8000/auth/register
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test41",
  "PASSWORD": "abcd1234",
  "EMAIL": "test41@mail.ru",
  "ROLE_ID": 4,
  "PHONE": "+7987-564-32-18"
}

###
POST http://127.0.0.1:8000/auth/login
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test52",
  "PASSWORD": "abcd1234"
}

###
GET http://127.0.0.1:8000/user/get_info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIxNTg4NiwianRpIjoiYWUzNDJkNzYtMzBhOC00YjcxLWI1NzUtN2VjMTY1ZjRmODE4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM5MjE1ODg2LCJjc3JmIjoiMjczMWY1MTAtNGRjOS00YWFhLThkNmEtMDMwN2M4NjdkYjBmIiwiZXhwIjoxNzM5MzAyMjg2LCJyb2xlX2lkIjoyLCJpZCI6N30.obV5oHs4d8iMkPIN7K6gy4C0Fjij9PsWugFANiRPVDM


###
GET http://127.0.0.1:8000/reestr/get?status=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIyNjA2MywianRpIjoiNGQ4Mjg1NTgtYzU1Ny00YzhkLWEzNjQtOWM1NjA4NjFhOTBjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1IiwibmJmIjoxNzM5MjI2MDYzLCJjc3JmIjoiOGIxYjdiNGUtNWJhZi00YzhhLTlhZTktMGZjYTY1ODQyN2RjIiwiZXhwIjoxNzM5MzEyNDYzLCJyb2xlX2lkIjo1LCJpZCI6NX0.QT3n2QpfuUwLV1MD0SU4EKgK_lRrEGZOA1K0SIMnsfk

###
GET http://127.0.0.1:8000/memo/accept?id=1&accept=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTE5NzY3MSwianRpIjoiZjk3NjQ4M2YtNjIxOC00OGM3LTlmYTctNDE1NWM3ZDYyM2VkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM5MTk3NjcxLCJjc3JmIjoiOWVhOGQ2MjUtMGVkZS00NzQxLWE3MzgtYTg4MmM3YWMyODkwIiwiZXhwIjoxNzM5Mjg0MDcxLCJyb2xlX2lkIjoyLCJpZCI6N30.FHcievb5so6k2rLbuPvjBdlh_XGcKvnMf7HlNeg2a40

###
POST http://127.0.0.1:8000/desc/set_sop
Accept: application/json
Content-Type: application/json

[100]

###
POST http://127.0.0.1:8000/desc/set_contract_type?type=2
Accept: application/json
Content-Type: application/json

[162]


###
GET http://127.0.0.1:8000/user/get_users?filters={"FIO": }
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTE4Njk3NiwianRpIjoiZTNmMWE2NmMtYzY3Yy00YWI1LTljOTUtMzU1NDdkMDIxZWNiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MSIsIm5iZiI6MTczOTE4Njk3NiwiY3NyZiI6IjQ3NWYzOWNjLTAyMTEtNDJhMS1hMzA2LThlOWIzYjg4ZjcxNSIsImV4cCI6MTczOTI3MzM3Niwicm9sZV9pZCI6NSwiaWQiOjExfQ.2iEcuAEi0YWEwGwAVIc4nZEy57D1mP8eWGoaS_og_o0

###
GET http://127.0.0.1:8000/memo/count?mode=executor
Accept: application/application/json

###
GET http://127.0.0.1:8000/memo/count?mode=status
Accept: application/application/json

###
GET http://127.0.0.1:8000/desc/get_aggregate
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIyMzQ0NSwianRpIjoiNjBkMmQwMzgtZDZjMC00OWJhLWE5YjUtZTQ4NTNkMzIxNzU3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MiIsIm5iZiI6MTczOTIyMzQ0NSwiY3NyZiI6ImMyYzkyMjk4LThjOTUtNDEyMy05ZTgyLWRmM2I2NzBiYzY3MyIsImV4cCI6MTczOTMwOTg0NSwicm9sZV9pZCI6NSwiaWQiOjEwfQ.y0Zj7xBpO2YjoI4M-BzBYKB6hvHcYLstdzqolG-m_eg

###
GET http://127.0.0.1:8000/kanban/
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIwMDcwMiwianRpIjoiOGZiZTQ0MzctNTlhNS00NmIzLWEzMzUtNDJiY2RlZWRlODI5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM5MjAwNzAyLCJjc3JmIjoiNjJjNWFhNGItYmE4NC00MzRjLThjODEtMzViYzJmNTRjZmE1IiwiZXhwIjoxNzM5Mjg3MTAyLCJyb2xlX2lkIjoyLCJpZCI6N30.Q0CIXSbKFBMU5GuwKQwJJveulDNxfscvJ6NM4QUI-yI

###
POST http://127.0.0.1:8000/kanban/
Accept: application/application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIwMDcwMiwianRpIjoiOGZiZTQ0MzctNTlhNS00NmIzLWEzMzUtNDJiY2RlZWRlODI5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM5MjAwNzAyLCJjc3JmIjoiNjJjNWFhNGItYmE4NC00MzRjLThjODEtMzViYzJmNTRjZmE1IiwiZXhwIjoxNzM5Mjg3MTAyLCJyb2xlX2lkIjoyLCJpZCI6N30.Q0CIXSbKFBMU5GuwKQwJJveulDNxfscvJ6NM4QUI-yI

[
    {
    "ID": 165,
    "COLUMN": "Выполнена",
    "COLUMNID": 3,
    "CONTENT": "Делать"
  },
  {
    "ID": 166,
    "COLUMN": "Сделать",
    "COLUMNID": 1,
    "CONTENT": "Приготовит"
  }
]

###
POST http://127.0.0.1:8000/checklist/create
Accept: application/application/json
Content-Type: application/json

{
  "CHECKLIST_ID": 0,
  "VALUES": [{"ID": 159}, {"ID": 162}]
}

###
GET http://127.0.0.1:8000/checklist/get
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTIyNzcxNiwianRpIjoiMDkzMmNjNDUtMTFlYi00MDdiLWJkOWEtZGUyNmU2OGQwN2E5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MiIsIm5iZiI6MTczOTIyNzcxNiwiY3NyZiI6IjFmODk1YmJlLTQ3N2EtNDE5MC04MGQyLWU4MDE1NmNlZmNkZSIsImV4cCI6MTczOTMxNDExNiwicm9sZV9pZCI6NSwiaWQiOjEwfQ.yECx9hgEhnkrYHakGzOlLIx1t_cnzj_VF_W9YWt8Tng

###
DELETE http://127.0.0.1:8000/checklist/delete?id=32
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTE4MzE2NCwianRpIjoiZTI4M2E0M2EtZDJiOC00NzVmLWI0NGQtYTc3YzQ1MmQzZjliIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1IiwibmJmIjoxNzM5MTgzMTY0LCJjc3JmIjoiYWJmOGY3ODQtNDViYS00N2Q4LTk5ZWQtOTA4Zjk0MzM5OWRkIiwiZXhwIjoxNzM5MjY5NTY0LCJyb2xlX2lkIjo1LCJpZCI6NX0.EN0Uu8TuRysih4CxeafQywq0oUGBpY_GoZgQ7QtmmLs