####
GET http://127.0.0.1:8000/form_memo?id=0072
Accept: application/application/json

####
POST http://127.0.0.1:8000/form_memo
Accept: application/json
Content-Type: application/json

{
  "ID_MEMO": 0,
  "DATE_OF_CREATION": "2024-10-27",
  "DATE_OF_APPOINTMENT": "2025-01-15",
  "STATUS_CODE": 1,
  "STATUS_TEXT": "Исполнение",
  "INFO": "ААААА",
  "JUSTIFICATION": "Описание для описаний",
  "HEAD_COMMENT": "",
  "EXECUTOR_COMMENT": "",
  "CREATOR": {
    "ID": 4,
    "SURNAME": "Петрова",
    "NAME": "Мария",
    "PATRONYMIC": "Александровна",
    "DEPARTMENT": "Отдел разработки IT-продуктов",
    "PHONE": "+7987-564-32-14",
    "EMAIL": "test4@mail.ru"
  },
  "EXECUTOR": {
    "ID": 7,
    "SURNAME": "Федорова",
    "NAME": "Анна",
    "PATRONYMIC": "Сергеевна",
    "DEPARTMENT": "Отдел 13"
  },
  "DESCRIPTION": [
    {
      "ID": 0,
      "POSITION": 1,
      "NAME": "Унитаз",
      "COUNT": 1,
      "UNIT_CODE": 6,
      "UNIT_TEXT": "ШТ",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "",
      "COEF": null,
      "CONTRACT_INFO": "",
      "DATE_OF_DELIVERY": "2025-12-12",
      "CONTRACT_TYPE": "",
      "EXECUTOR": {
        "ID": 11,
        "SURNAME": "Новиков",
        "NAME": "Олег",
        "PATRONYMIC": "Геннадьевич",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-15",
        "EMAIL": "test51@mail.ru"
      },
      "HISTORY": []
    }
  ],
  "JUSTIFICATION_FILE": {
    "EXT": null,
    "NAME": null,
    "DATA": null
  }
}

####
POST http://127.0.0.1:8000/form_memo
Accept: application/json
Content-Type: application/json

{
  "ID_MEMO": 0,
  "DATE_OF_CREATION": "2025-01-20",
  "DATE_OF_APPOINTMENT": "2025-01-10",
  "STATUS_CODE": 1,
  "STATUS_TEXT": "Ожидание согласования",
  "INFO": "Новая на проверк",
  "JUSTIFICATION": "Проверка фильтра",
  "HEAD_COMMENT": "",
  "EXECUTOR_COMMENT": "",
  "CREATOR": {
    "ID": 3,
    "SURNAME": "Сидоров",
    "NAME": "Петр",
    "PATRONYMIC": "Алексеевич",
    "DEPARTMENT": "Цех 1",
    "PHONE": "",
    "EMAIL": ""
  },
  "EXECUTOR": {
    "ID": 7,
    "SURNAME": "Федорова",
    "NAME": "Анна",
    "PATRONYMIC": "Сергеевна",
    "DEPARTMENT": "Отдел 13"
  },
  "DESCRIPTION": [
    {
      "ID": 0,
      "POSITION": 2,
      "NAME": "Соль",
      "COUNT": 15,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "DATE_OF_DELIVERY": "2025-01-17",
      "CONTRACT_TYPE": "",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    },
    {
      "ID": 0,
      "POSITION": 3,
      "NAME": "Мука",
      "COUNT": 25,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "CONTRACT_TYPE": "",
      "DATE_OF_DELIVERY": "2025-01-22",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    },
    {
      "ID": 100,
      "POSITION": 1,
      "NAME": "Соль",
      "COUNT": 20,
      "UNIT_CODE": 2,
      "UNIT_TEXT": "Г",
      "STATUS_CODE": 1,
      "STATUS_TEXT": "Запрос ТКП",
      "COEF": 0.1,
      "CONTRACT_INFO": "",
      "CONTRACT_TYPE": "",
      "DATE_OF_DELIVERY": "2025-01-12",
      "EXECUTOR": {
        "ID": 10,
        "SURNAME": "Соколова",
        "NAME": "Екатерина",
        "PATRONYMIC": "Владимировна",
        "DEPARTMENT": "Отдел 13",
        "PHONE": "+7987-564-32-17",
        "EMAIL": "test52@mail.ru"
      },
      "HISTORY": [
        {
          "STATUS_ID": 1,
          "DATE": "2025-01-20"
        }
      ]
    }
  ],
  "JUSTIFICATION_FILE": {
    "EXT": null,
    "NAME": null,
    "DATA": null
  }
}


####
GET http://127.0.0.1:8000/get_selectors
Accept: application/application/json

####
GET http://127.0.0.1:8000/form_memo?id=19
Accept: application/application/json

###
POST http://127.0.0.1:8000/register
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test52",
  "PASSWORD": "abcd1234",
  "EMAIL": "test52@mail.ru",
  "ROLE_ID": 5,
  "PHONE": "+7987-564-32-17"
}

###
POST http://127.0.0.1:8000/login
Accept: application/json
Content-Type: application/json

{
  "LOGIN": "test52",
  "PASSWORD": "abcd1234"
}

###e
GET http://127.0.0.1:8000/get_user_info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMzc3NjEyNiwianRpIjoiOGY0Y2Q0YTYtMDhiNi00NjhjLWIyYzItNGRkNDY3ODdmNmJiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzMzNzc2MTI2LCJjc3JmIjoiZTYxYTY1OGUtMTNjNi00NzFmLWIyMDItY2FiMjNkOTgwZDlmIiwiZXhwIjoxNzMzNzgzMzI2LCJyb2xlX2lkIjoyLCJpZCI6N30.gw3dxBQTCv8luBnsnsxsV7G0X61rU9xntPsSBTQIkGI


###
GET http://127.0.0.1:8000/get_reestr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczODg1NjQ5OSwianRpIjoiN2VhMjk3MGYtYmVmMi00NWFlLWIyY2QtYTU4NmUzMWNmMjJhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM4ODU2NDk5LCJjc3JmIjoiMjRjN2E5OTgtYTc3MC00Nzk0LThjMGQtZjZiYmFiMjMyYTE3IiwiZXhwIjoxNzM4OTQyODk5LCJyb2xlX2lkIjoyLCJpZCI6N30.-qSmTWtnMLgswKmmXE1ND424f53fEMalhDnt0Heim_4
###
GET http://127.0.0.1:8000/accept_memo?id=1&accept=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczODY2ODM5MiwianRpIjoiMDIyM2QwZjgtY2QzYy00YTMxLWI3NDQtMjk0NzVlOGYyNjJhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QxIiwibmJmIjoxNzM4NjY4MzkyLCJjc3JmIjoiY2NkMDBjM2YtMWZkOS00MTU0LWJkOGQtYzM1ZGYwNmVjYjRiIiwiZXhwIjoxNzM4NzU0NzkyLCJyb2xlX2lkIjoxLCJpZCI6MX0.rupNhLxGVh6SS3KG92-OGAcb7uxFsnC67StZZv1b5Ho


###
GET http://127.0.0.1:8000/search_memo?filters={"ITEM_NAME": "Ка"}
Accept: application/application/json


###
POST http://127.0.0.1:8000/set_sop?id=98
Accept: application/json
Content-Type: application/json

###
POST http://127.0.0.1:8000/set_contract_type?type=2
Accept: application/json
Content-Type: application/json

[14, 15, 16]


###
GET http://127.0.0.1:8000/get_users?filters={"ROLE": 5, "FIO": ""}
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNzMwNDYyMSwianRpIjoiYzZjNzQ0NDYtNDU2Ny00OWRmLWFiNjYtY2E3MjU3MzM5MDJhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM3MzA0NjIxLCJjc3JmIjoiNDgwMWU5OGItYjAwMC00YzY3LTgzNTItYzU1NjE3MTk2MzAwIiwiZXhwIjoxNzM3MzkxMDIxLCJyb2xlX2lkIjoyLCJpZCI6N30.M_dcYc4YsJ_7D0KM060iZNd3vtAbXSsWUlzX4fgflGM

###
GET http://127.0.0.1:8000/count_memo?mode=executor
Accept: application/application/json

###
GET http://127.0.0.1:8000/count_memo?mode=status
Accept: application/application/json

###
GET http://127.0.0.1:8000/get_aggregate
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczODkxNzU3NiwianRpIjoiMzQ3Nzk3YTgtNjUzYS00M2E0LTkxODYtZjFmZGIyZTc3Zjc0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM4OTE3NTc2LCJjc3JmIjoiNGQwZTU5YzktYjU1ZS00Y2YzLWJlNzgtZTBhNTM1NzNkZGE1IiwiZXhwIjoxNzM5MDAzOTc2LCJyb2xlX2lkIjoyLCJpZCI6N30.CTWsPfxXlSDbEWAz4sjqj8WrunkPP7lliJka4QbZ79Q

###
GET http://127.0.0.1:8000/get_kanban
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNzQwMzM2MywianRpIjoiOWViODU0MWYtNTJkMy00Y2RmLTliNGUtMmM5YmM5ZTI4MjFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM3NDAzMzYzLCJjc3JmIjoiMzQ5Zjc3NGEtYmNiNS00MjQ5LWEzNWUtYjE5ZGNlZjY4YjU0IiwiZXhwIjoxNzM3NDg5NzYzLCJyb2xlX2lkIjoyLCJpZCI6N30.PKOvUU-KDECFbnjmKtozdAO3HITNTn8Xf_xcTtKGrP8

###
POST http://127.0.0.1:8000/set_kanban
Accept: application/application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNzQwMzM2MywianRpIjoiOWViODU0MWYtNTJkMy00Y2RmLTliNGUtMmM5YmM5ZTI4MjFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyIiwibmJmIjoxNzM3NDAzMzYzLCJjc3JmIjoiMzQ5Zjc3NGEtYmNiNS00MjQ5LWEzNWUtYjE5ZGNlZjY4YjU0IiwiZXhwIjoxNzM3NDg5NzYzLCJyb2xlX2lkIjoyLCJpZCI6N30.PKOvUU-KDECFbnjmKtozdAO3HITNTn8Xf_xcTtKGrP8

[
{
  "COLUMNID": 1,
  "CONTENT": "Попробовать"
},
{
  "COLUMNID": 2,
  "CONTENT": "Делать"
}
]

###
POST http://127.0.0.1:8000/create_checklist
Accept: application/application/json
Content-Type: application/json

{
  "CHECKLIST_ID": 0,
  "VALUES": [
    {
      "ID": 91
    },
    {
      "ID": 92
    },
    {
      "ID": 97
    }
    ]
}

###
GET http://127.0.0.1:8000/get_checklist
Accept: application/application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTA5NDk0MCwianRpIjoiY2FjNmU5MjAtZDBiZC00ODZiLThjMTUtNmVlMzY3NjY1YWNkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3Q1MiIsIm5iZiI6MTczOTA5NDk0MCwiY3NyZiI6IjVlYjZhNDBmLTZjMmItNGIxNC1iNTc2LTI3Yzc1N2NhY2FiMSIsImV4cCI6MTczOTE4MTM0MCwicm9sZV9pZCI6NSwiaWQiOjEwfQ.I2p6Z2PAijZxaOkCSOP6dqwhY2C-El7Sfa02LILjNYk